sudo: required
language: bash
services: docker

install: true

after_success:
  - docker --version
  - echo 'Travis commit is:\n'
  - echo $TRAVIS_COMMIT
  - echo 'Travis Build Number is:\n'
  - echo $TRAVIS_BUILD_NUMBER
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=wumvi/db.prod
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

after_script:
- docker logout